baseURL = 'https://ronnyascencio.com/'
languageCode = 'en-us'
title = 'Ronny Ascencio'
theme = "hello-friend-ng"

[params]
    colorScheme = "dark"
    showReadingTime = true
    # Esto activará tu branding personal
    header = { layout = "fixed", showLogo = false }
    homeSubtitle = "Technical Artist | Cinematography"
    footer = { showCopyright = true, showPoweredBy = false }

[menu]
  [[menu.main]]
    name = "Portafolio"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "Ateru Pipeline"
    url = "https://docs.ateru-pipeline.com" # Tu dominio de docs
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 30
