export const assets = {
  profile_picture: "/assets/profile.jpg",
  adobe_logo: "/assets/adobe-2.svg",
  fastapi_logo: "/assets/fastapi-1.svg",
  nuke_logo: "/assets/foundry-nuke.svg",
  git_logo: "/assets/git-icon.svg",
  github_logo: "/assets/github-icon-1.svg",
  linux_logo: "/assets/linux-tux.svg",
  maya_logo: "/assets/maya-2017.svg",
  python_logo: "/assets/python.png",
  react_logo: "/assets/react.png",
  renderman_logo: "/assets/renderman-logo.svg",
  mongo_logo: "/assets/mongodb-icon-1.svg",
  sql_logo: "/assets/postgresql.svg",
};
